name: Continuos Delivery

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.REPO_OWNER }}
          password: ${{ secrets.REPO_CR_PAT }}

      - name: Build and push to Dockerhub
        id: dockerhub_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            luisfalconmx/strapi:latest
            luisfalconmx/strapi:${{ env.RELEASE_VERSION }}
            luisfalconmx/strapi/strapi:latest
            luisfalconmx/strapi/strapi:${{ env.RELEASE_VERSION }}

      - name: Image digest
        run: echo ${{ steps.dockerhub_build.outputs.digest }}
